### PR TITLE
refactor: tf transformer module and tests

### LINKED ISSUE #1296: Refactor Transformer tests
Refactor TransformerTorch and TransformerTF tests with a matrix of parameters by using `pytest parametrize`. The matrix should contain a few popular models worth testing with different `pooling` and `layer_index`

### PR DESCRIPTION
**Pull request by tadejsv**
This refactors the TF transformer encoder in line with changes done to the Torch encoder in #1344 and #1498.

Closes #1296

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
Hey @tadejsv ,

Thanks for the contribution, you are being very helpful.

Please remember to add some tests checking the shape when a single text is passed. An issue was found in the TransformerTorchEncoder

**Comment by tadejsv** [comment]
@JoanFM yes, a test for that is added (I basically just copied over torch transformer tests)

**Comment by tadejsv** [comment]
@JoanFM this is ready to merge :)

**Review by JoanFM — APPROVED** [review]

**Comment by JoanFM** [comment]
Thanks a lot for the great contributions @tadejsv !

**Pull request merged**
