### PR TITLE
fix: fix output shape

### PR DESCRIPTION
**Pull request by JoanFM**

### CODE REVIEW

**Comment by JoanFM** [comment]
Fixes #1500 #1483

**Comment by florian-hoenicke** [comment]
can we format the file and optimize imports?

**Review by rutujasurve94 — APPROVED** [review]

**Comment by JoanFM** [comment]
> can we format the file and optimize imports? (encoders/nlp/TransformerTorchEncoder/**init**.py )

is it good now?

**Review by florian-hoenicke — APPROVED** [review]
Nicely done!

**Pull request merged**
