### PR TITLE
feat: add json schema

### PR DESCRIPTION
**Pull request by Kelton8Z**

### CODE REVIEW

**Review by deepankarm — CHANGES_REQUESTED** [review]
@Kelton8Z 

I checked json-forms with this schema. This looks good! Few points:

- The schema can be generated using Pydantic. Should be straightforward. 
- We should host the schema in api.jina.ai like [yaml-lint-schema](https://api.jina.ai/schemas/latest.json). You can check [this](https://github.com/jina-ai/jina/blob/master/.github/workflows/tag.yml#L10) for inspiration. 

@Roshanjossey you can take this & use in a [playground](https://jsonform.github.io/jsonform/playground/index.html)

**Comment by Roshanjossey** [comment]
@deepankarm, sure, I'll try it and post here.

**Comment by Kelton8Z** [comment]
@deepankarm 
I will put the corresponding pydantic code under the same schema directory then ?
Also how is [this](https://github.com/jina-ai/jina/blob/master/.github/workflows/tag.yml#L10) related to hosting the schema ?

**Comment by deepankarm** [comment]
> I will put the corresponding pydantic code under the same jina-hub/schema directory then ?

I would recommend the following. 
- Add a `scripts` directory and put the Pydantic code there. Result of this code should write the schema to a local directory.  
- Create a github workflow in this repo that we can run manually (workflow_dispatch). 
- Run the python code inside the workflow & push the schema to `jina-ai/api`

**Comment by Kelton8Z** [comment]
I do not find it very convenient to reproduce JSON Schema with pydantic examplified by issues like [Field title and description being overridden for Enums](https://github.com/samuelcolvin/pydantic/issues/1748) and [Pydantic generates an extra allOf when providing default value of enum type](https://www.bountysource.com/issues/97523038-pydantic-generates-an-extra-allof-when-providing-default-value-of-enum-type)

**Comment by Kelton8Z** [comment]
@Roshanjossey 
I recommend using https://rjsf-team.github.io/react-jsonschema-form/ instead for better support of internal referencing not that the JSON Schema is updated.

**Comment by Kelton8Z** [comment]
> > I will put the corresponding pydantic code under the same jina-hub/schema directory then ?
> 
> I would recommend the following.
> 
> * Add a `scripts` directory and put the Pydantic code there. Result of this code should write the schema to a local directory.
> * Create a github workflow in this repo that we can run manually (workflow_dispatch).
> * Run the python code inside the workflow & push the schema to `jina-ai/api`

Should be done under https://github.com/jina-ai/jina-hub/pull/7564/

**Comment by Roshanjossey** [comment]
Codesandbox with the schema using https://rjsf-team.github.io/react-jsonschema-form/ https://codesandbox.io/s/react-jsonschema-form-mozilla-with-material-ui-and-react-select-forked-rzu26

**Comment by Yongxuanzhang** [comment]
Could you provide more background or information about this PR? There isn't too much information as well in the ticket

**Comment by Kelton8Z** [comment]
> Could you provide more background or information about this PR? There isn't too much information as well in the ticket

Added a description, meanwhile background can be found on the slack channel "triage-goodbye-cookiecutter"

**Comment by Kelton8Z** [comment]
> Codesandbox with the schema using https://rjsf-team.github.io/react-jsonschema-form/ https://codesandbox.io/s/react-jsonschema-form-mozilla-with-material-ui-and-react-select-forked-rzu26

https://github.com/jina-ai/api/blob/master/schemas/hub_executor_schema.json should work

**Comment by Yongxuanzhang** [comment]
> > Could you provide more background or information about this PR? There isn't too much information as well in the ticket
> 
> This JSON Schema is for generating hub executor image, meanwhile more background can be found on the slack channel "triage-goodbye-cookiecutter"

I mean it would be better to always add some information in the PR description. So if others want to check this PR it would be easily understood.

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Pull request merged**
