### PR TITLE
docs: docstring for segmenters/image

### PR DESCRIPTION
**Pull request by theUnkownName**

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
remember to bump versions

**Comment by theUnkownName** [comment]
> remember to bump versions

Yes I thought to have a separate commit for all them together

**Review by JoanFM — CHANGES_REQUESTED** [review]
remember to bump version

**Comment by theUnkownName** [comment]
> remember to bump version

@JoanFM what you mean? I think they all have versions updated, or am I missing one?

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
