### PR TITLE
fix: convert to python3

### PR DESCRIPTION
**Pull request by florian-hoenicke**
iteritems is not used in python3 anymore

edit: turned out the files are not used anyway. I deleted them.

### CODE REVIEW

**Review by cristianmtr — DISMISSED** [review]

**Review by JoanFM — CHANGES_REQUESTED** [review]
this file is very likely that can be removed

**Comment by florian-hoenicke** [comment]
You mean I should try to get rid of both of the datasets.py files?

**Comment by JoanFM** [comment]
> You mean I should try to get rid of both of the datasets.py files?

yes

**Comment by florian-hoenicke** [comment]
Thanks, I deleted the files

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
