### PR TITLE
fix: ndcg evaluator

### PR DESCRIPTION
**Pull request by florian-hoenicke**

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
I see the typo from `mainfest` to manifest` but why do we add an empty `requirements.txt` file?

**Review by JoanFM — CHANGES_REQUESTED** [review]
Plus, remember to bump version

**Comment by JoanFM** [comment]
> Plus, remember to bump version

No I see no need, I guess no proper built happened maybe?

**Comment by florian-hoenicke** [comment]
@JoanFM okay, I removed the empty requirements file

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
