### PR TITLE
refactor: migrate pca encoder

### PR DESCRIPTION
**Pull request by JamesTang-jinaai**
need to migrate unit test.
Resolved: #154

### CODE REVIEW

**Comment by JoanFM** [comment]
Check this PR #148, since TransformEncoder is going to be moved back to core

**Comment by JamesTang-jinaai** [comment]
> Check this PR #148, since TransformEncoder is going to be moved back to core

OK, I'll do refactor first, then change the base class to transform encoder, then move pca back to core. Thank you, Joan, for your kindly remind.

**Comment by JoanFM** [comment]
> > Check this PR #148, since TransformEncoder is going to be moved back to core
> 
> OK, I'll do refactor first, then change the base class to transform encoder, then move pca back to core. Thank you, Joan, for your kindly remind.

Why PCA back to core?

**Comment by JoanFM** [comment]
Remember to remove the swap file that u pushed encoders/numeric/IncrementalPCAEncoder/tests/.test_incrementalpcaencoder.py.swp

**Comment by JamesTang-jinaai** [comment]
> > > Check this PR #148, since TransformEncoder is going to be moved back to core
> > 
> > 
> > OK, I'll do refactor first, then change the base class to transform encoder, then move pca back to core. Thank you, Joan, for your kindly remind.
> 
> Why PCA back to core?

No need, misunderstanding.

**Review by JoanFM — APPROVED** [review]

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Pull request merged**
