### PR TITLE
feat: enable changing channel axis

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
I wonder if we could have similar code as 
https://github.com/jina-ai/jina-hub/blob/26faf53637a66d3a0ea30c1b8875e3276faafe4c/encoders/image/ImageTorchEncoder/__init__.py#L88
This is useful in some cases

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
I am not sure if we should go this way. Since normally ImageNormalizer is needed before most of our ImageEncoders.

Have u checked why it is not working for you adding rhe ImageNormalizer before?

**Comment by Yongxuanzhang** [comment]
> I am not sure if we should go this way. Since normally ImageNormalizer is needed before most of our ImageEncoders.
> 
> Have u checked why it is not working for you adding rhe ImageNormalizer before?

I copy-paste the configuration of ImageNormalizer in our cross model example but still failing. I haven't got too much time to look into it. I guess it's not a big issue but just need some time to check

**Comment by Yongxuanzhang** [comment]
> I am not sure if we should go this way. Since normally ImageNormalizer is needed before most of our ImageEncoders.
> 
> Have u checked why it is not working for you adding rhe ImageNormalizer before?

This decreases the dependency of the clip encoder on ImageNormalizer. We can either configure it at ImageNormalizeror here.
Yet the disadvantage I can see is that this will introduce more parameter, which may make ppl confused.

**Comment by JoanFM** [comment]
> > I am not sure if we should go this way. Since normally ImageNormalizer is needed before most of our ImageEncoders.
> > Have u checked why it is not working for you adding rhe ImageNormalizer before?
> 
> This decreases the dependency of the clip encoder on ImageNormalizer. We can either configure it at ImageNormalizeror or here.
> Yet the disadvantage I can see is that this will introduce more parameter, which may make ppl confused.

The problem I see is that putting this here, may make the channel being changed more than once. After all, ImageNormalization is always needed.  Also it may be confusing because then there are 2 ways of achieving the same thing. 

And since there is no way you will avoid the need to use ImageNormalizer, I would not add this here

**Comment by Yongxuanzhang** [comment]
> > > I am not sure if we should go this way. Since normally ImageNormalizer is needed before most of our ImageEncoders.
> > > Have u checked why it is not working for you adding rhe ImageNormalizer before?
> > 
> > 
> > This decreases the dependency of the clip encoder on ImageNormalizer. We can either configure it at ImageNormalizeror or here.
> > Yet the disadvantage I can see is that this will introduce more parameter, which may make ppl confused.
> 
> The problem I see is that putting this here, may make the channel being changed more than once. After all, ImageNormalization is always needed. Also it may be confusing because then there are 2 ways of achieving the same thing.
> 
> And since there is no way you will avoid the need to use ImageNormalizer, I would not add this here

Yes, I agree. Maybe I need to figure out what's the issue with ImageNormalizer.

**Comment by Yongxuanzhang** [comment]
> > > I am not sure if we should go this way. Since normally ImageNormalizer is needed before most of our ImageEncoders.
> > > Have u checked why it is not working for you adding rhe ImageNormalizer before?
> > 
> > 
> > This decreases the dependency of the clip encoder on ImageNormalizer. We can either configure it at ImageNormalizeror or here.
> > Yet the disadvantage I can see is that this will introduce more parameter, which may make ppl confused.
> 
> The problem I see is that putting this here, may make the channel being changed more than once. After all, ImageNormalization is always needed. Also it may be confusing because then there are 2 ways of achieving the same thing.
> 
> And since there is no way you will avoid the need to use ImageNormalizer, I would not add this here

I doubt this code could work as expected, 
image

**Comment by JoanFM** [comment]
Why is this failing?

```
!ImageNormalizer
with:
  target_size: 224
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]
  channel_axis: 0
metas:
  name: normalizer
requests:
  on:
    IndexRequest:
      - !CraftDriver
        with:
          executor: normalizer
    SearchRequest:
      - !CraftDriver
        with:
          executor: normalizer
    ControRequest:
      - !ControlReqDriver {}
```

**Comment by Yongxuanzhang** [comment]
> Why is this failing?
> 
> ```
> !ImageNormalizer
> with:
>   target_size: 224
>   img_mean: [0.485, 0.456, 0.406]
>   img_std: [0.229, 0.224, 0.225]
>   channel_axis: 0
> metas:
>   name: normalizer
> requests:
>   on:
>     IndexRequest:
>       - !CraftDriver
>         with:
>           executor: normalizer
>     SearchRequest:
>       - !CraftDriver
>         with:
>           executor: normalizer
>     ControRequest:
>       - !ControlReqDriver {}
> ```
For example, 
because my input data before craft() is (300,300,3), if channel_axis: 0, 
then `raw_img = _load_image(blob, self.channel_axis)` will fail, because the code expect it to be -1.

**Comment by JoanFM** [comment]
> > Why is this failing?
> > ```
> > !ImageNormalizer
> > with:
> >   target_size: 224
> >   img_mean: [0.485, 0.456, 0.406]
> >   img_std: [0.229, 0.224, 0.225]
> >   channel_axis: 0
> > metas:
> >   name: normalizer
> > requests:
> >   on:
> >     IndexRequest:
> >       - !CraftDriver
> >         with:
> >           executor: normalizer
> >     SearchRequest:
> >       - !CraftDriver
> >         with:
> >           executor: normalizer
> >     ControRequest:
> >       - !ControlReqDriver {}
> > ```
> 
> For example,
> because my input data before craft() is (300,300,3), if channel_axis: 0,
> then `raw_img = _load_image(blob, self.channel_axis)` will fail, because the code expect it to be -1.

So put channel_axis to be -1. It is a parameter.

**Comment by Yongxuanzhang** [comment]
> > > Why is this failing?
> > > ```
> > > !ImageNormalizer
> > > with:
> > >   target_size: 224
> > >   img_mean: [0.485, 0.456, 0.406]
> > >   img_std: [0.229, 0.224, 0.225]
> > >   channel_axis: 0
> > > metas:
> > >   name: normalizer
> > > requests:
> > >   on:
> > >     IndexRequest:
> > >       - !CraftDriver
> > >         with:
> > >           executor: normalizer
> > >     SearchRequest:
> > >       - !CraftDriver
> > >         with:
> > >           executor: normalizer
> > >     ControRequest:
> > >       - !ControlReqDriver {}
> > > ```
> > 
> > 
> > For example,
> > because my input data before craft() is (300,300,3), if channel_axis: 0,
> > then `raw_img = _load_image(blob, self.channel_axis)` will fail, because the code expect it to be -1.
> 
> So put channel_axis to be -1. It is a parameter.

No, -1 won't work as well 😂 . Because Clip expects it to be 0. There's no way to make it work if I didn't modify the ImageNormalizer or the clip encoder

**Comment by JoanFM** [comment]
> > > > Why is this failing?
> > > > ```
> > > > !ImageNormalizer
> > > > with:
> > > >   target_size: 224
> > > >   img_mean: [0.485, 0.456, 0.406]
> > > >   img_std: [0.229, 0.224, 0.225]
> > > >   channel_axis: 0
> > > > metas:
> > > >   name: normalizer
> > > > requests:
> > > >   on:
> > > >     IndexRequest:
> > > >       - !CraftDriver
> > > >         with:
> > > >           executor: normalizer
> > > >     SearchRequest:
> > > >       - !CraftDriver
> > > >         with:
> > > >           executor: normalizer
> > > >     ControRequest:
> > > >       - !ControlReqDriver {}
> > > > ```
> > > 
> > > 
> > > For example,
> > > because my input data before craft() is (300,300,3), if channel_axis: 0,
> > > then `raw_img = _load_image(blob, self.channel_axis)` will fail, because the code expect it to be -1.
> > 
> > 
> > So put channel_axis to be -1. It is a parameter.
> 
> No, -1 won't work as well 😂 . Because Clip expects it to be 0. There's no way to make it work if I didn't modify the ImageNormalizer or the clip encoder

Ok, so the shape of ur input image is different as in the crossmodal search. 

I think it makes sense to add target_channel_axis as parameter

**Comment by Yongxuanzhang** [comment]
> > > Why is this failing?
> > > ```
> > > !ImageNormalizer
> > > with:
> > >   target_size: 224
> > >   img_mean: [0.485, 0.456, 0.406]
> > >   img_std: [0.229, 0.224, 0.225]
> > >   channel_axis: 0
> > > metas:
> > >   name: normalizer
> > > requests:
> > >   on:
> > >     IndexRequest:
> > >       - !CraftDriver
> > >         with:
> > >           executor: normalizer
> > >     SearchRequest:
> > >       - !CraftDriver
> > >         with:
> > >           executor: normalizer
> > >     ControRequest:
> > >       - !ControlReqDriver {}
> > > ```
> > 
> > 
> > For example,
> > because my input data before craft() is (300,300,3), if channel_axis: 0,
> > then `raw_img = _load_image(blob, self.channel_axis)` will fail, because the code expect it to be -1.
> 
> So put channel_axis to be -1. It is a parameter.

Just for explanation:
Ideally, I want this:
(300,300,3)->(3,224,244) with crafter->(num_batch, 3,224,224) with clip encoder. 
With current crafter and clip encoder:

- channel_axis=-1 for crafter: (300,300,3)->(224,224,3) with crafter->(num_batch,224,224,3) with clip encoder. the clip encoder will have error
- channel_axis=0 for crafter: (300,300,3)->(224,224,3) with crafter, then there will be errors in crafter.

**Comment by Yongxuanzhang** [comment]
> > > > > Why is this failing?
> > > > > ```
> > > > > !ImageNormalizer
> > > > > with:
> > > > >   target_size: 224
> > > > >   img_mean: [0.485, 0.456, 0.406]
> > > > >   img_std: [0.229, 0.224, 0.225]
> > > > >   channel_axis: 0
> > > > > metas:
> > > > >   name: normalizer
> > > > > requests:
> > > > >   on:
> > > > >     IndexRequest:
> > > > >       - !CraftDriver
> > > > >         with:
> > > > >           executor: normalizer
> > > > >     SearchRequest:
> > > > >       - !CraftDriver
> > > > >         with:
> > > > >           executor: normalizer
> > > > >     ControRequest:
> > > > >       - !ControlReqDriver {}
> > > > > ```
> > > > 
> > > > 
> > > > For example,
> > > > because my input data before craft() is (300,300,3), if channel_axis: 0,
> > > > then `raw_img = _load_image(blob, self.channel_axis)` will fail, because the code expect it to be -1.
> > > 
> > > 
> > > So put channel_axis to be -1. It is a parameter.
> > 
> > 
> > No, -1 won't work as well 😂 . Because Clip expects it to be 0. There's no way to make it work if I didn't modify the ImageNormalizer or the clip encoder
> 
> Ok, so the shape of ur input image is different as in the crossmodal search.
> 
> I think it makes sense to add target_channel_axis as parameter

yes, exactly. I will close this and add that in the ImageNormalizer

**Comment by JoanFM** [comment]
Good, thanks for the explanation!!

**Pull request closed without merging**
