### PR TITLE
refactor: remove mean reciprocal rank evaluator

### PR DESCRIPTION
**Pull request by JoanFM**
**Changes introduced**
MeanReciprocalRankEvaluation is handled the accumulation of results from `ReciprocalRankEvaluator` which is the one evaluating document per document

### CODE REVIEW

**Comment by deepankarm** [comment]
We still don't have a mechanism to remove a Pod from docker-hub & MongoDB. So even though the code is deleted from here, the Pod exists.

**Comment by florian-hoenicke** [comment]
@JoanFM I'm not so familiar with the evaluation. Could you quickly describe why the MeanReciprocalRankEvaluator has to be deleted?

**Comment by JoanFM** [comment]
> @JoanFM I'm not so familiar with the evaluation. Could you quickly describe why the MeanReciprocalRankEvaluator has to be deleted?

hey @florian-hoenicke ; the point is that evaluation works at doc2doc level; and mean or average computation must be computed by the client to avoid having state. and since we already have ReciprocalRank this is not needed. And actually this will not work with any driver

**Comment by JoanFM** [comment]
> We still don't have a mechanism to remove a Pod from docker-hub & MongoDB. So even though the code is deleted from here, the Pod exists.

at least the code wont be there

**Comment by florian-hoenicke** [comment]
@JoanFM  Thanks. Okay makes totally sense to avoid comparing chunks for evaluation.

**Review by florian-hoenicke — APPROVED** [review]

**Comment by JoanFM** [comment]
> @JoanFM Thanks. Okay makes totally sense to avoid comparing chunks for evaluation.

just for reference; is not about chunks. It is about MeanReciprocalRank depending on the evaluation of different queries.

Right now; evaluation works in every pair of (doc, groundtruth) independently from any other document or groundtruth. Like this we mantain independence and can keep our evaluation pods stateless.

MeanReciprocalRank should not be there for the same reason no MeanNDCGEvaluation or MeanPrecision is there, to keep independence between documentation evaluations. Think that an Evaluation Flow can never know for how long u want to accumulate results for average, mean or any other metric. That is for now left at the client consideration.

**Pull request merged**
