### PR TITLE
chore: bump ImageOnnxEncoder version to 0.0.5

### PR DESCRIPTION
**Pull request by hanxiao**

### CODE REVIEW

**Comment by JoanFM** [comment]
Depends on local model path

**Comment by JoanFM** [comment]
Depends on https://github.com/jina-ai/jina/pull/1077

**Comment by bhavsarpratik** [comment]
@deepankarm Will this error be fixed in new release of jina as fixed by jina-ai/jina#1107
`tmp_model_path = self.get_file_from_workspace(f'{self.model_name}.tmp')`

**Comment by deepankarm** [comment]
What are the next steps on this?

**Comment by JoanFM** [comment]
wait for Sunday's relase of Jina.

**Review by deepankarm — APPROVED** [review]

**Pull request merged**
