### PR TITLE
feat(segmenter): add location for SlidingWindowAudioSlicer

### PR DESCRIPTION
**Pull request by shakurshams**

### CODE REVIEW

**Review by nan-wang — DISMISSED** [review]
LGTM👍

**Comment by nan-wang** [comment]
oops, you need to bump the version in the `manifest.yml` @shakurshams

**Comment by nan-wang** [comment]
oops, you need to bump the version in the `manifest.yml` @shakurshams

**Comment by shakurshams** [comment]
> oops, you need to bump the version in the `manifest.yml` @shakurshams
done.

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Pull request merged**
