### PR TITLE
ci: mark push true only for prs raised by jina bot

### PR DESCRIPTION
**Pull request by deepankarm**

### CODE REVIEW

**Comment by JoanFM** [comment]
Should the push only be triggered when the PR is merged?

**Comment by deepankarm** [comment]
> Should the push only be triggered when the PR is merged?

yes, for all our PRs, push should only be triggered when PR is merged. But for all PRs raised by `jina-bot`, since we don't ever merge it, `push` should be true.

**Comment by JoanFM** [comment]
> > Should the push only be triggered when the PR is merged?
> 
> yes, for all our PRs, push should only be triggered when PR is merged. But for all PRs raised by `jina-bot`, since we don't ever merge it, `push` should be true.

Totally agree, when merged is it activate the push action?

**Comment by deepankarm** [comment]
> > > Should the push only be triggered when the PR is merged?
> > 
> > 
> > yes, for all our PRs, push should only be triggered when PR is merged. But for all PRs raised by `jina-bot`, since we don't ever merge it, `push` should be true.
> 
> Totally agree, when merged is it activate the push action?

Yah. That's a different workflow file.

**Review by nan-wang — COMMENTED** [review]
LGTM👍

**Pull request merged**
