### PR TITLE
docs(readme): add naming conventions, app build instructions, hub push

### PR DESCRIPTION
**Pull request by alexcg1**

### CODE REVIEW

**Review by JoanFM — APPROVED** [review]

**Comment by alexcg1** [comment]
Is there any way to merge this with the failing test?

**Comment by JoanFM** [comment]
@deepankarm did u change the CI?

**Comment by deepankarm** [comment]
Looks like this branch doesn't have latest changes from master.

**Comment by alexcg1** [comment]
Only thing I touched was the README. Didn't do anything with CI @JoanFM

**Comment by JoanFM** [comment]
This is a CI problem, we need admin to fix this, or u can try to rebase with master because I think @deepankarm did some refactoring on how ci works

**Pull request merged**
