### PR TITLE
refactor: refactor no training

### PR DESCRIPTION
**Pull request by JoanFM**

### CODE REVIEW

**Review by Yongxuanzhang — COMMENTED** [review]
It's a little weird that we refactor this, and all numeric encoders will be the same? 😂  I just wonder what is the next plan

**Comment by JoanFM** [comment]
> It's a little weird that we refactor this, and all numeric encoders will be the same?  I just wonder what is the next plan

When they encode the data, they do exactly the same, therefore there is no difference. And since we are going for a design that explicitly separates `executors` from their `training`, we remove the specifities. We could remove these `hub` executors, but for backward compatibility we can mantain this

**Comment by Yongxuanzhang** [comment]
> > It's a little weird that we refactor this, and all numeric encoders will be the same?  I just wonder what is the next plan
> 
> When they encode the data, they do exactly the same, therefore there is no difference. And since we are going for a design that explicitly separates `executors` from their `training`, we remove the specifities. We could remove these `hub` executors, but for backward compatibility we can mantain this

Got it

**Comment by Yongxuanzhang** [comment]
> > It's a little weird that we refactor this, and all numeric encoders will be the same?  I just wonder what is the next plan
> 
> When they encode the data, they do exactly the same, therefore there is no difference. And since we are going for a design that explicitly separates `executors` from their `training`, we remove the specifities. We could remove these `hub` executors, but for backward compatibility we can mantain this

Why not finish the training first then refactor all of this? DO they block something?

**Comment by JoanFM** [comment]
> > > It's a little weird that we refactor this, and all numeric encoders will be the same?  I just wonder what is the next plan
> > 
> > 
> > When they encode the data, they do exactly the same, therefore there is no difference. And since we are going for a design that explicitly separates `executors` from their `training`, we remove the specifities. We could remove these `hub` executors, but for backward compatibility we can mantain this
> 
> Why not finish the training first then refactor all of this? DO they block something?

I want to remove the confusion about `training`. Because is non-usable code. I think is better not to have noise

**Review by Yongxuanzhang — APPROVED** [review]
LGTM. It might be better to keep it open so others will also review this PR.

**Pull request merged**
