### PR TITLE
fix: parameter overwrite enabled again

### PR DESCRIPTION
**Pull request by maximilianwerk**
This is a revert from some time ago. Alternative solution would be:
```
def __init__(self, *args, **kwargs):
    super().init(self, *args, **kwargs)
    Transformer(self, *args, **kwargs)
```

Multiclass inheritance is not always working as one would expect.

### CODE REVIEW

**Comment by maximilianwerk** [comment]
That one fixed the quality issue I was talking about.

**Review by JoanFM — APPROVED** [review]

**Review by JoanFM — CHANGES_REQUESTED** [review]
Please bump versions

**Comment by JoanFM** [comment]
> Please bump versions

plus it would be nice to add a test overriding params again

**Comment by maximilianwerk** [comment]
I removed some tests for `TransformerTFEncoder`, which anyhow never ran correctly before and never succeeded.

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
