### PR TITLE
feat: add cmlm encoder

### PR DESCRIPTION
**Pull request by carlosb1**

### CODE REVIEW

**Comment by carlosb1** [comment]
`         HubIO@18[I]:E         tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'CaseFoldUTF8' in binary running on c7337fdeee54. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`

I think, it is related with the tf version, it is not compatible now which your current version.

**Comment by JoanFM** [comment]
> ` HubIO@18[I]:E tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'CaseFoldUTF8' in binary running on c7337fdeee54. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.)`tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`
> 
> I think, it is related with the tf version, it is not compatible now which your current version.

You can adapt the version in the requirements.txt, which version is needed?

**Comment by carlosb1** [comment]
> > ` HubIO@18[I]:E tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'CaseFoldUTF8' in binary running on c7337fdeee54. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.)`tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`
> > I think, it is related with the tf version, it is not compatible now which your current version.
> 
> You can adapt the version in the requirements.txt, which version is needed?

I commented this in the issue, I think you need 2.4  but your req is 2.3 in another module, I will try to fix it, but I am not sure that i can be done.

**Comment by JoanFM** [comment]
> > > ` HubIO@18[I]:E tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'CaseFoldUTF8' in binary running on c7337fdeee54. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.)`tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`
> > > I think, it is related with the tf version, it is not compatible now which your current version.
> > 
> > 
> > You can adapt the version in the requirements.txt, which version is needed?
> 
> I commented this in the issue, I think you need 2.4 but your req is 2.3 in another module, I will try to fix it, but I am not sure that i can be done.

in requirements, it is 2.4.0

**Review by JoanFM — CHANGES_REQUESTED** [review]
Something messed up with ur commit and now u have changes from other branches

**Comment by carlosb1** [comment]
> Something messed up with ur commit and now u have changes from other branches

I did rebase from master. I should not be too much complicate.

**Pull request closed without merging**
